### ISSUE TITLE
[Feature suggestion] Add Unit+UI testing

### ISSUE THREAD

**Issue by lucianonooijen** [FiberJW/design-starter-kit#1]
Combining React Native/Expo with unit and ui testing with f.e. Jest and Enzyme, combined with Typescript, is usually quite a pain.

It would be awesome to extend this template with unit+ui testing to have a template that _just works_.

**Comment by FiberJW** [comment]
Feel free to fork this project if you want, but as this template is for the initial design/prototyping phase of product development, testing isn't one if its concerns. Thanks for the feedback though!
